<div id="item">
	<?=$this->render('/item/titulo.phtml'); ?>
    <div id="centro-esquerda">                  
		<?=$this->render('/item/dados-item.phtml'); ?>                       
    </div>
    <div id="centro-direita">       
        <?=$this->render('/publicidade/publicidade1.phtml'); ?>
        <?=$this->render('/widget/menu-direita.phtml'); ?>
	<?=$this->render('/widget/ultimas-coberturas.phtml'); ?> 
    </div>
</div>