<div id="item-index">
	<div id="centro-esquerda">
    <!--
    <p><?php //echo count($this->itens); ?><p>
    <p><?php //echo count($this->itens)." * 50 = R$ ".count($this->itens) * 50 ." - 30% = R$ " .count($this->itens) * 0.30 * 50; ?><p>
	<?php //foreach ( $this->itens as $cid) : ?>
                <a href="/item/conteudo/id/<?php //echo $cid->getIdItem(); ?>" title="ver"> <?php //echo $cid->getTitulo(); ?></a>  <br />          	
    <?php //endforeach; ?>
    -->
    
    <p><?php //echo $this->combate; ?><p>
	</div>
</div>