<div class='item_item'>
<div>
GUIA
	</div>
	<div>
	EDITAR
	</div>
	<div>
	FOTO INDEX
	</div>
	<div>

	FOTO
	</div>
	<div>
	FOTO TITULO
	</div>
</div>
 <div class='item_item'>
	<div>
	A Lanterna 
	</div>

	<div>
	<a href="../usuario/editar.php?filtro=guia&amp;guia_id=85"><img src="../imagens/icones/editar.png">editar</a>
	</div>
	<div>
	<a href="../usuario/cadastrar.php?filtro=cadastrar_foto_index_guia&amp;guia_id=85"><img src="../imagens/icones/cadastrar.png">foto index</a>
	</div>
	<div>
	<a href="../usuario/cadastrar.php?filtro=cadastrar_foto_guia&amp;guia_id=85"><img src="../imagens/icones/cadastrar.png">foto</a>

	</div>
	<div>
	<a href="../usuario/cadastrar.php?filtro=cadastrar_foto_titulo_guia&amp;guia_id=85"><img src="../imagens/icones/cadastrar.png">foto titulo</a>
	</div>
</div>
 <div class='item_item'>
	<div>
	Adega Piedade 
	</div>

	<div>
	<a href="../usuario/editar.php?filtro=guia&amp;guia_id=5"><img src="../imagens/icones/editar.png">editar</a>
	</div>
	<div>
	<a href="../usuario/cadastrar.php?filtro=cadastrar_foto_index_guia&amp;guia_id=5"><img src="../imagens/icones/cadastrar.png">foto index</a>
	</div>
	<div>
	<a href="../usuario/cadastrar.php?filtro=cadastrar_foto_guia&amp;guia_id=5"><img src="../imagens/icones/cadastrar.png">foto</a>

	</div>
	<div>
	<a href="../usuario/cadastrar.php?filtro=cadastrar_foto_titulo_guia&amp;guia_id=5"><img src="../imagens/icones/cadastrar.png">foto titulo</a>
	</div>
</div>
 <div class='item_item'>
	<div>
	Adler Vinhedo 
	</div>

	<div>
	<a href="../usuario/editar.php?filtro=guia&amp;guia_id=142"><img src="../imagens/icones/editar.png">editar</a>
	</div>
	<div>
	<a href="../usuario/cadastrar.php?filtro=cadastrar_foto_index_guia&amp;guia_id=142"><img src="../imagens/icones/cadastrar.png">foto index</a>
	</div>
	<div>
	<a href="../usuario/cadastrar.php?filtro=cadastrar_foto_guia&amp;guia_id=142"><img src="../imagens/icones/cadastrar.png">foto</a>

	</div>
	<div>
	<a href="../usuario/cadastrar.php?filtro=cadastrar_foto_titulo_guia&amp;guia_id=142"><img src="../imagens/icones/cadastrar.png">foto titulo</a>
	</div>
</div>
 <div class='item_item'>
	<div>
	Alemãozinho Bar 
	</div>

	<div>
	<a href="../usuario/editar.php?filtro=guia&amp;guia_id=101"><img src="../imagens/icones/editar.png">editar</a>
	</div>
	<div>
	<a href="../usuario/cadastrar.php?filtro=cadastrar_foto_index_guia&amp;guia_id=101"><img src="../imagens/icones/cadastrar.png">foto index</a>
	</div>
	<div>
	<a href="../usuario/cadastrar.php?filtro=cadastrar_foto_guia&amp;guia_id=101"><img src="../imagens/icones/cadastrar.png">foto</a>

	</div>
	<div>
	<a href="../usuario/cadastrar.php?filtro=cadastrar_foto_titulo_guia&amp;guia_id=101"><img src="../imagens/icones/cadastrar.png">foto titulo</a>
	</div>
</div>
 <div class='item_item'>
	<div>
	Altay Club 
	</div>

	<div>
	<a href="../usuario/editar.php?filtro=guia&amp;guia_id=152"><img src="../imagens/icones/editar.png">editar</a>
	</div>
	<div>
	<a href="../usuario/cadastrar.php?filtro=cadastrar_foto_index_guia&amp;guia_id=152"><img src="../imagens/icones/cadastrar.png">foto index</a>
	</div>
	<div>
	<a href="../usuario/cadastrar.php?filtro=cadastrar_foto_guia&amp;guia_id=152"><img src="../imagens/icones/cadastrar.png">foto</a>

	</div>
	<div>
	<a href="../usuario/cadastrar.php?filtro=cadastrar_foto_titulo_guia&amp;guia_id=152"><img src="../imagens/icones/cadastrar.png">foto titulo</a>
	</div>
</div>
 <div class='item_item'>
	<div>
	Ana Festas 
	</div>

	<div>
	<a href="../usuario/editar.php?filtro=guia&amp;guia_id=74"><img src="../imagens/icones/editar.png">editar</a>
	</div>
	<div>
	<a href="../usuario/cadastrar.php?filtro=cadastrar_foto_index_guia&amp;guia_id=74"><img src="../imagens/icones/cadastrar.png">foto index</a>
	</div>
	<div>
	<a href="../usuario/cadastrar.php?filtro=cadastrar_foto_guia&amp;guia_id=74"><img src="../imagens/icones/cadastrar.png">foto</a>

	</div>
	<div>
	<a href="../usuario/cadastrar.php?filtro=cadastrar_foto_titulo_guia&amp;guia_id=74"><img src="../imagens/icones/cadastrar.png">foto titulo</a>
	</div>
</div>
 <div class='item_item'>
	<div>
	Anastácia Bar 
	</div>

	<div>
	<a href="../usuario/editar.php?filtro=guia&amp;guia_id=22"><img src="../imagens/icones/editar.png">editar</a>
	</div>
	<div>
	<a href="../usuario/cadastrar.php?filtro=cadastrar_foto_index_guia&amp;guia_id=22"><img src="../imagens/icones/cadastrar.png">foto index</a>
	</div>
	<div>
	<a href="../usuario/cadastrar.php?filtro=cadastrar_foto_guia&amp;guia_id=22"><img src="../imagens/icones/cadastrar.png">foto</a>

	</div>
	<div>
	<a href="../usuario/cadastrar.php?filtro=cadastrar_foto_titulo_guia&amp;guia_id=22"><img src="../imagens/icones/cadastrar.png">foto titulo</a>
	</div>
</div>
 <div class='item_item'>
	<div>
	Anzu Club 
	</div>

	<div>
	<a href="../usuario/editar.php?filtro=guia&amp;guia_id=4"><img src="../imagens/icones/editar.png">editar</a>
	</div>
	<div>
	<a href="../usuario/cadastrar.php?filtro=cadastrar_foto_index_guia&amp;guia_id=4"><img src="../imagens/icones/cadastrar.png">foto index</a>
	</div>
	<div>
	<a href="../usuario/cadastrar.php?filtro=cadastrar_foto_guia&amp;guia_id=4"><img src="../imagens/icones/cadastrar.png">foto</a>

	</div>
	<div>
	<a href="../usuario/cadastrar.php?filtro=cadastrar_foto_titulo_guia&amp;guia_id=4"><img src="../imagens/icones/cadastrar.png">foto titulo</a>
	</div>
</div>
 <div class='item_item'>
	<div>
	Aqua Lounge 
	</div>

	<div>
	<a href="../usuario/editar.php?filtro=guia&amp;guia_id=147"><img src="../imagens/icones/editar.png">editar</a>
	</div>
	<div>
	<a href="../usuario/cadastrar.php?filtro=cadastrar_foto_index_guia&amp;guia_id=147"><img src="../imagens/icones/cadastrar.png">foto index</a>
	</div>
	<div>
	<a href="../usuario/cadastrar.php?filtro=cadastrar_foto_guia&amp;guia_id=147"><img src="../imagens/icones/cadastrar.png">foto</a>

	</div>
	<div>
	<a href="../usuario/cadastrar.php?filtro=cadastrar_foto_titulo_guia&amp;guia_id=147"><img src="../imagens/icones/cadastrar.png">foto titulo</a>
	</div>
</div>
 <div class='item_item'>
	<div>
	Arena Axé Moi 
	</div>

	<div>
	<a href="../usuario/editar.php?filtro=guia&amp;guia_id=63"><img src="../imagens/icones/editar.png">editar</a>
	</div>
	<div>
	<a href="../usuario/cadastrar.php?filtro=cadastrar_foto_index_guia&amp;guia_id=63"><img src="../imagens/icones/cadastrar.png">foto index</a>
	</div>
	<div>
	<a href="../usuario/cadastrar.php?filtro=cadastrar_foto_guia&amp;guia_id=63"><img src="../imagens/icones/cadastrar.png">foto</a>

	</div>
	<div>
	<a href="../usuario/cadastrar.php?filtro=cadastrar_foto_titulo_guia&amp;guia_id=63"><img src="../imagens/icones/cadastrar.png">foto titulo</a>
	</div>
</div>
 <div class='item_item'>
	<div>
	Arena Schincariol 
	</div>

	<div>
	<a href="../usuario/editar.php?filtro=guia&amp;guia_id=79"><img src="../imagens/icones/editar.png">editar</a>
	</div>
	<div>
	<a href="../usuario/cadastrar.php?filtro=cadastrar_foto_index_guia&amp;guia_id=79"><img src="../imagens/icones/cadastrar.png">foto index</a>
	</div>
	<div>
	<a href="../usuario/cadastrar.php?filtro=cadastrar_foto_guia&amp;guia_id=79"><img src="../imagens/icones/cadastrar.png">foto</a>

	</div>
	<div>
	<a href="../usuario/cadastrar.php?filtro=cadastrar_foto_titulo_guia&amp;guia_id=79"><img src="../imagens/icones/cadastrar.png">foto titulo</a>
	</div>
</div>
 <div class='item_item'>
	<div>
	Arena Verão Show 
	</div>

	<div>
	<a href="../usuario/editar.php?filtro=guia&amp;guia_id=125"><img src="../imagens/icones/editar.png">editar</a>
	</div>
	<div>
	<a href="../usuario/cadastrar.php?filtro=cadastrar_foto_index_guia&amp;guia_id=125"><img src="../imagens/icones/cadastrar.png">foto index</a>
	</div>
	<div>
	<a href="../usuario/cadastrar.php?filtro=cadastrar_foto_guia&amp;guia_id=125"><img src="../imagens/icones/cadastrar.png">foto</a>

	</div>
	<div>
	<a href="../usuario/cadastrar.php?filtro=cadastrar_foto_titulo_guia&amp;guia_id=125"><img src="../imagens/icones/cadastrar.png">foto titulo</a>
	</div>
</div>
 <div class='item_item'>
	<div>
	Armazém Dom Pedro 
	</div>

	<div>
	<a href="../usuario/editar.php?filtro=guia&amp;guia_id=23"><img src="../imagens/icones/editar.png">editar</a>
	</div>
	<div>
	<a href="../usuario/cadastrar.php?filtro=cadastrar_foto_index_guia&amp;guia_id=23"><img src="../imagens/icones/cadastrar.png">foto index</a>
	</div>
	<div>
	<a href="../usuario/cadastrar.php?filtro=cadastrar_foto_guia&amp;guia_id=23"><img src="../imagens/icones/cadastrar.png">foto</a>

	</div>
	<div>
	<a href="../usuario/cadastrar.php?filtro=cadastrar_foto_titulo_guia&amp;guia_id=23"><img src="../imagens/icones/cadastrar.png">foto titulo</a>