<!--INICO CONTEUDO DO USUARIO -->
<div id="usuario">
    <div id="centro-esquerda"> 
        
        <div id="bloco-usuario-esquerda">
            <?=$this->render('/usuario/titulo.phtml'); ?>

        </div>   
        <div id="bloco-usuario-direita">
        <?=$this->render('/usuario/menu-conteudo.phtml'); ?>
<?php
echo "<h1>".$this->idImg."</h1>";
$this->form->setAction($this->url());
echo $this->form;?>
        </div>
    </div>
    <div id="centro-direita">       
    	<?=$this->render('/usuario/mais-usuarios.phtml'); ?>    
    </div>
</div>

