<!-- INICIO MAIS USUARIOS -->
<!--<div class="outros_itens">
<h2>Mais Usuarios</h2>
	<ul id="thumbs-usuario">-->
        <?php // foreach ( $this->listaUsuarios as $cid) : ?>
			<?php //foreach ( $cid->getImagens() as $img) : ?>
               <!-- <li>
                    <a href="/usuario/conteudo/id/--><?php //echo $cid->getIdUsuario(); ?><!--" title="--><?php //echo $this->escape($cid->getNome()); ?><!--">-->
                    	<!--<img src="/img/--><?php //echo $img->getCaminho();?><!--" width="100"/>
                    
                    </a>
                </li>-->
            <?php //endforeach; ?>    
        <?php //endforeach; ?>
    <!--</ul>
</div>-->
<!-- FIM MAIS USUARIOS -->