<div id="adm-widget">
<ul>
	<li><a href="/widget/criar-mais-cidades" target="_blank">criar mais cidades</a></li>
 	<li><a href="/widget/criar-menu-cidades" target="_blank">criar menu cidades</a></li>
 	<li><a href="/widget/criar-ultimas-coberturas" target="_blank">criar ultimas coberturas</a></li> 
 	<li><a href="/widget/criar-lista-artigos" target="_blank">criar lista artigos</a></li>   
 	<li><a href="/widget/criar-destaques-coberturas" target="_blank">criar destaques coberturas</a></li>          
 	<li><a href="/widget/criar-cobertura" target="_blank">criar cobertura</a></li> 
</ul>
</div>