<div id="menu-direita">
	<div class="menu-direita-agenda">
    <a href="/evento/"><img src="/imagens/m-r-agenda.png"/></a>
    </div>
	<div class="menu-direita-fotos">
        <a href="/evento/cobertura"><img src="/imagens/m-r-fotos.png"/></a>
    </div> 
	<div class="menu-direita-artistas">
        <a href="/artista/"><img src="/imagens/m-r-artistas.png"/></a>
    </div>
	<div class="menu-direita-points">
        <a href="/item/"><img src="/imagens/m-r-points.png"/></a>
    </div>           
</div>