<div class='mais-coberturas'>
<h2>Coberturas Recentes</h2>
<div class='item-cobertura'>
<div class='data'>
<div class='data-mes'><?php echo $this->Data('2011-03-19')->extenso_sub; ?></div>
<div class='data-dia'><?php echo $this->Data('2011-03-19')->pt_br_dia; ?></div>
<div class='data-ano'><?php echo $this->Data('2011-03-19')->mes_sub; ?></div>
</div>  
<div class='item-foto-cobertura' >
<a href=/evento/cobertura-fotografica/id/4354>
<img src='/img/b06cb63112c5baba94329b841cc7a94avnbindex.jpg' width='190'/>
</a>   
</div>
<div class='titulo-item-cobertura'>
<a href='/evento/cobertura-fotografica/id/4354' title='ver'>Ressaca do Motumbo</a>
</div>
</div>
<div class='item-cobertura'>
<div class='data'>
<div class='data-mes'><?php echo $this->Data('2011-03-19')->extenso_sub; ?></div>
<div class='data-dia'><?php echo $this->Data('2011-03-19')->pt_br_dia; ?></div>
<div class='data-ano'><?php echo $this->Data('2011-03-19')->mes_sub; ?></div>
</div>  
<div class='item-foto-cobertura' >
<a href=/evento/cobertura-fotografica/id/4354>
<img src='/img/b06cb63112c5baba94329b841cc7a94avnbindex.jpg' width='190'/>
</a>   
</div>
<div class='titulo-item-cobertura'>
<a href='/evento/cobertura-fotografica/id/4354' title='ver'>Ressaca do Motumbo</a>
</div>
</div>
<div class='item-cobertura'>
<div class='data'>
<div class='data-mes'><?php echo $this->Data('2011-03-18')->extenso_sub; ?></div>
<div class='data-dia'><?php echo $this->Data('2011-03-18')->pt_br_dia; ?></div>
<div class='data-ano'><?php echo $this->Data('2011-03-18')->mes_sub; ?></div>
</div>  
<div class='item-foto-cobertura' >
<a href=/evento/cobertura-fotografica/id/4359>
<img src='/img/fdf39c3636d192785fa30c6b3ddc5710vnbcapa.jpg' width='190'/>
</a>   
</div>
<div class='titulo-item-cobertura'>
<a href='/evento/cobertura-fotografica/id/4359' title='ver'>Guilherme e Santiago</a>
</div>
</div>
<div class='item-cobertura'>
<div class='data'>
<div class='data-mes'><?php echo $this->Data('2011-03-19')->extenso_sub; ?></div>
<div class='data-dia'><?php echo $this->Data('2011-03-19')->pt_br_dia; ?></div>
<div class='data-ano'><?php echo $this->Data('2011-03-19')->mes_sub; ?></div>
</div>  
<div class='item-foto-cobertura' >
<a href=/evento/cobertura-fotografica/id/4354>
<img src='/img/b06cb63112c5baba94329b841cc7a94avnbindex.jpg' width='190'/>
</a>   
</div>
<div class='titulo-item-cobertura'>
<a href='/evento/cobertura-fotografica/id/4354' title='ver'>Ressaca do Motumbo</a>
</div>
</div>
<div class='item-cobertura'>
<div class='data'>
<div class='data-mes'><?php echo $this->Data('2011-03-18')->extenso_sub; ?></div>
<div class='data-dia'><?php echo $this->Data('2011-03-18')->pt_br_dia; ?></div>
<div class='data-ano'><?php echo $this->Data('2011-03-18')->mes_sub; ?></div>
</div>  
<div class='item-foto-cobertura' >
<a href=/evento/cobertura-fotografica/id/4359>
<img src='/img/fdf39c3636d192785fa30c6b3ddc5710vnbcapa.jpg' width='190'/>
</a>   
</div>
<div class='titulo-item-cobertura'>
<a href='/evento/cobertura-fotografica/id/4359' title='ver'>Guilherme e Santiago</a>
</div>
</div>
<div class='item-cobertura'>
<div class='data'>
<div class='data-mes'><?php echo $this->Data('2011-03-12')->extenso_sub; ?></div>
<div class='data-dia'><?php echo $this->Data('2011-03-12')->pt_br_dia; ?></div>
<div class='data-ano'><?php echo $this->Data('2011-03-12')->mes_sub; ?></div>
</div>  
<div class='item-foto-cobertura' >
<a href=/evento/cobertura-fotografica/id/4353>
<img src='/img/6b8dc7dd252c30f34e0da0cf6685e62evnbindex.jpg' width='190'/>
</a>   
</div>
<div class='titulo-item-cobertura'>
<a href='/evento/cobertura-fotografica/id/4353' title='ver'>Abril Fest 2011 Escolha da Rainha</a>
</div>
</div>
<div class='item-cobertura'>
<div class='data'>
<div class='data-mes'><?php echo $this->Data('2011-03-19')->extenso_sub; ?></div>
<div class='data-dia'><?php echo $this->Data('2011-03-19')->pt_br_dia; ?></div>
<div class='data-ano'><?php echo $this->Data('2011-03-19')->mes_sub; ?></div>
</div>  
<div class='item-foto-cobertura' >
<a href=/evento/cobertura-fotografica/id/4354>
<img src='/img/b06cb63112c5baba94329b841cc7a94avnbindex.jpg' width='190'/>
</a>   
</div>
<div class='titulo-item-cobertura'>
<a href='/evento/cobertura-fotografica/id/4354' title='ver'>Ressaca do Motumbo</a>
</div>
</div>
<div class='item-cobertura'>
<div class='data'>
<div class='data-mes'><?php echo $this->Data('2011-03-18')->extenso_sub; ?></div>
<div class='data-dia'><?php echo $this->Data('2011-03-18')->pt_br_dia; ?></div>
<div class='data-ano'><?php echo $this->Data('2011-03-18')->mes_sub; ?></div>
</div>  
<div class='item-foto-cobertura' >
<a href=/evento/cobertura-fotografica/id/4359>
<img src='/img/fdf39c3636d192785fa30c6b3ddc5710vnbcapa.jpg' width='190'/>
</a>   
</div>
<div class='titulo-item-cobertura'>
<a href='/evento/cobertura-fotografica/id/4359' title='ver'>Guilherme e Santiago</a>
</div>
</div>
<div class='item-cobertura'>
<div class='data'>
<div class='data-mes'><?php echo $this->Data('2011-03-12')->extenso_sub; ?></div>
<div class='data-dia'><?php echo $this->Data('2011-03-12')->pt_br_dia; ?></div>
<div class='data-ano'><?php echo $this->Data('2011-03-12')->mes_sub; ?></div>
</div>  
<div class='item-foto-cobertura' >
<a href=/evento/cobertura-fotografica/id/4353>
<img src='/img/6b8dc7dd252c30f34e0da0cf6685e62evnbindex.jpg' width='190'/>
</a>   
</div>
<div class='titulo-item-cobertura'>
<a href='/evento/cobertura-fotografica/id/4353' title='ver'>Abril Fest 2011 Escolha da Rainha</a>
</div>
</div>
<div class='item-cobertura'>
<div class='data'>
<div class='data-mes'><?php echo $this->Data('2011-03-11')->extenso_sub; ?></div>
<div class='data-dia'><?php echo $this->Data('2011-03-11')->pt_br_dia; ?></div>
<div class='data-ano'><?php echo $this->Data('2011-03-11')->mes_sub; ?></div>
</div>  
<div class='item-foto-cobertura' >
<a href=/evento/cobertura-fotografica/id/4335>
<img src='/img/95892f2bcc6fd2b3918483add98687d2vnb1.jpg' width='190'/>
</a>   
</div>
<div class='titulo-item-cobertura'>
<a href='/evento/cobertura-fotografica/id/4335' title='ver'>Junior C</a>
</div>
</div>
</div>
