<div id="welcome">
    <h1>Bem-vindo ao <span id="zf-name">Item</span></h1>

    <h3>Esta é a página principal do projeto</h3>

    <div id="more-information">
        <p><img src="http://framework.zend.com/images/PoweredBy_ZF_4LightBG.png" /></p>
        <p>
            Helpful Links: <br />
            <a href="/">Home</a> |
            <a href="/index/item/">Items</a>
        </p>
    </div>
</div>