<div class='item_cidade'>
<div>
cidade
	</div>
	<div>
	EDITAR
	</div>
	<div>
	FOTO INDEX
	</div>
	<div>

	FOTO
	</div>
	<div>
	FOTO TITULO
	</div>
</div>
 <div class='item_cidade'>
	<div>
	Itapetininga
	</div>

	<div>
	<a href="../usuario/editar.php?filtro=cidade&amp;cidade_id=85"><img src="../imagens/icones/editar.png">editar</a>
	</div>
	<div>
	<a href="../usuario/cadastrar.php?filtro=cadastrar_foto_index_cidade&amp;cidade_id=85"><img src="../imagens/icones/cadastrar.png">foto index</a>
	</div>
	<div>
	<a href="../usuario/cadastrar.php?filtro=cadastrar_foto_cidade&amp;cidade_id=85"><img src="../imagens/icones/cadastrar.png">foto</a>

	</div>
	<div>
	<a href="../usuario/cadastrar.php?filtro=cadastrar_foto_titulo_cidade&amp;cidade_id=85"><img src="../imagens/icones/cadastrar.png">foto titulo</a>
	</div>
</div>
 <div class='item_cidade'>
	<div>
	Itu 
	</div>

	<div>
	<a href="../usuario/editar.php?filtro=cidade&amp;cidade_id=5"><img src="../imagens/icones/editar.png">editar</a>
	</div>
	<div>
	<a href="../usuario/cadastrar.php?filtro=cadastrar_foto_index_cidade&amp;cidade_id=5"><img src="../imagens/icones/cadastrar.png">foto index</a>
	</div>
	<div>
	<a href="../usuario/cadastrar.php?filtro=cadastrar_foto_cidade&amp;cidade_id=5"><img src="../imagens/icones/cadastrar.png">foto</a>

	</div>
	<div>
	<a href="../usuario/cadastrar.php?filtro=cadastrar_foto_titulo_cidade&amp;cidade_id=5"><img src="../imagens/icones/cadastrar.png">foto titulo</a>
	</div>
</div>
 <div class='item_cidade'>
	<div>
	Sorocaba
	</div>

	<div>
	<a href="../usuario/editar.php?filtro=cidade&amp;cidade_id=142"><img src="../imagens/icones/editar.png">editar</a>
	</div>
	<div>
	<a href="../usuario/cadastrar.php?filtro=cadastrar_foto_index_cidade&amp;cidade_id=142"><img src="../imagens/icones/cadastrar.png">foto index</a>
	</div>
	<div>
	<a href="../usuario/cadastrar.php?filtro=cadastrar_foto_cidade&amp;cidade_id=142"><img src="../imagens/icones/cadastrar.png">foto</a>

	</div>
	<div>
	<a href="../usuario/cadastrar.php?filtro=cadastrar_foto_titulo_cidade&amp;cidade_id=142"><img src="../imagens/icones/cadastrar.png">foto titulo</a>
	</div>
</div>