<!-- INICIO DO FORMULÁRIO-->
<form name="formulario" method="POST" action="#" enctype="multipart/form-data"> 
<fieldset>
<legend>Procurar cidade</legend>
<label>
	<input name="cidade_titulo" maxlength="200" size="50" value="">
	         
</label>

	  <label>
          <input type="submit" name="submit" value="pesquisar">  
		  </label>
		  </fieldset>
</form>
<!-- FIM DO FORMULÁRIO-->